# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Vagrant box (Ubuntu)
  config.vm.box = "ubuntu/trusty64"

  # Define vagrant host 2
  config.vm.define "packerhost" do |host|
    host.vm.box = "ubuntu/trusty64"
    host.vm.hostname = "packerhost"
    host.vm.network "private_network", ip: "192.168.10.101"
    host.vm.provision :shell, path: "bootstrap_packerhost.sh"

    # Virtualbox specific settings.
    config.vm.provider :virtualbox do |vb|
      # Label the virtual machine
      vb.name = "packerhost"

      #Optional: Enable virtual box GUI on boot. i.e not headless.
      # vb.gui = true

      # Set CPU and Memory size for the virtual machine.
      # Follow VBoxManage guide for more options.
      # http://www.virtualbox.org/manual/ch08.html
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      # Enable hardware virtualization.
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
      vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
      vb.customize ["modifyvm", :id, "--largepages", "on"]
      vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
    end
  end

end
