# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.define "orchestrator" do |orchestrator|
    orchestrator.vm.box = "centos/7"
    orchestrator.vm.hostname = "orchestrator"
    orchestrator.vm.network "private_network", ip: "192.168.67.10"
    orchestrator.vm.provision :shell, path: "bootstrap.sh"
    # virtual-box specific settings
    config.vm.provider :virtualbox do |vb|

      # Lable the virtual machine
      vb.name = "orchestrator"

      # Optional: Enable the Virtual Box GUI on boot, i.e. not "headless"
      # vb.gui = true

      # Set CPU and memory size
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", 1024]

      # Enable promiscuous mode on eth2 for floating IPs to be accessible
      # vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
  end

  config.vm.define "host2" do |host2|
    host2.vm.box = "centos/7"
    host2.vm.hostname = "host2"
    host2.vm.network "private_network", ip: "192.168.67.100"
    host2.vm.provision :shell, path: "bootstrap2.sh"

    # virtual-box specific settings
    config.vm.provider :virtualbox do |vb|
        # Lable the virtual machine
        vb.name = "host2"

        # Optional: Enable the Virtual Box GUI on boot, ie not "headless"
        # vb.gui = true

        # Set CPU and memory size.
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        vb.customize ["modifyvm", :id, "--memory", 1024]

    end
    #Vbox settings.
  end
end

