# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Vagrant box (Ubuntu)
  config.vm.box = "ubuntu/trusty64"

  HOSTNAME = "host1"
  # Define vagrant host 1
  config.vm.define "#{HOSTNAME}" do |host|
    host.vm.box = "ubuntu/trusty64"
    host.vm.hostname = "#{HOSTNAME}"
    host.vm.network "private_network", ip: "192.168.10.100"
    host.vm.provision :shell, path: "bootstrap_host1.sh"
  
    # Additional configurations.
    # host1.vm.network "forwarded_port", guest: 80, host: 8080
    # host1.vm.box_check_update = false
    # host1.vm.synced_folder "../data", "/vagrant_data"

    # Virtualbox specific settings.
    config.vm.provider :virtualbox do |vb|
      # Label the virtual machine
      vb.name = "#{HOSTNAME}"
    
      #Optional: Enable virtual box GUI on boot. i.e not headless.
      # vb.gui = true

      # Set CPU and Memory size for the virtual machine.
      # Follow VBoxManage guide for more options.
      # http://www.virtualbox.org/manual/ch08.html
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end 
  # host1 definition end.

  # Define vagrant host 2
  config.vm.define "host2" do |host|
    host.vm.box = "ubuntu/trusty64"
    host.vm.hostname = "host2"
    host.vm.network "private_network", ip: "192.168.10.101"
    host.vm.provision :shell, path: "bootstrap_host2.sh"

    # Virtualbox specific settings.
    config.vm.provider :virtualbox do |vb|
      # Label the virtual machine
      vb.name = "host2"

      #Optional: Enable virtual box GUI on boot. i.e not headless.
      # vb.gui = true

      # Set CPU and Memory size for the virtual machine.
      # Follow VBoxManage guide for more options.
      # http://www.virtualbox.org/manual/ch08.html
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

end
